[package]
name = "whispr_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
whispr_core = { workspace = true }
postcard = { workspace= true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
ed25519-dalek = { workspace = true }
futures-util = "0.3.32"
ratatui = "0.30.0"